project:
  type: website
  preview:
    port: 4200
    browser: false

website:
  title: "kodeks"
  favicon: images/android-chrome-384x384.png
  navbar:
    background: secondary
    logo: images/beyaz.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

